### PR TITLE
Make peerDependencies more universal, update dependencies

### PR DESCRIPTION
**Pull request by niieani**
It would be messy for you to update this package with every release of `ts-node` (which just happened). I've moved it to peerDependencies with the range of `*` and updated other deps. Hope that's okay.

### CODE REVIEW

**Comment by danielmoore** [comment]
I'd prefer to restrict the range to major versions that we know are API-compatible. If Typescript v2.x is compatible, let's just bump the requirement to `>= 1.5.0 < 3`

Also - why does `ts-node` need to be a peer dep?

**Comment by niieani** [comment]
The problem with a restricted range is that it doesn't allow development/beta versions. According to SemVer `>= 1.5.0 < 3` would mean `2.0` is okay, but `1.9-dev` is not. Unfortunately it's either `*` if you want it to always work or manually specifying ranges for ALL dev versions like this monster:
`>= 1.5.0-beta || >= 1.6.0-beta || >= 1.7.0-beta || >= 1.8.0-beta || >= 1.9.0-beta || >=2.0.0-beta || ^2.0.0 < 3`. I've moved `ts-node` as a peer-dep because this way it's up to the user to update it, not to you, the package maintainer. Currently it's a bit annoying that I had to fork and republish your package under a different name just to use the new capabilities of `ts-node`.

**Comment by danielmoore** [comment]
Good explanation! I'm convinced.

**Comment by niieani** [comment]
Actually, it seems the SemVer calculator mislead me. 

`*` doesn't cover the `-dev` releases -- if you can believe it! 
I think we'll need to switch to: `>= 1.5.0-beta || >= 1.6.0-beta || >= 1.7.0-beta || >= 1.8.0-beta || >= 1.9.0-beta || >=2.0.0-beta || >=2.0.0 < 3` after all...

**Pull request merged**
